# Generated by Django 6.0 on 2025-12-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Default SMTP', max_length=100)),
                ('from_email', models.EmailField(max_length=254)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferLetterTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Template', max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='offer_letter_logos/')),
                ('subject', models.CharField(default='Offer Letter', max_length=255)),
                ('body', models.TextField()),
                ('footer', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer_letter_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='direct_reports', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('offer_letter_id', models.AutoField(primary_key=True, serialize=False)),
                ('joining_date', models.DateField()),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('designation', models.CharField(max_length=255)),
                ('probation_period', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=255)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('shift_timings', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letters', to='employees.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_offer_letters', to='employees.employee')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_offer_letters', to='employees.employee')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_letters', to='employees.offerlettertemplate')),
            ],
            options={
                'db_table': 'offer_letters',
                'ordering': ['-issued_at'],
            },
        ),
    ]
