# Generated by Django 6.0 on 2025-12-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_emailsettings_offerlettertemplate_employee_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('portal', models.CharField(choices=[('Admin', 'Admin Portal'), ('Employee', 'Employee Portal')], default='Employee', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
