# Generated by Django 6.0 on 2025-12-24 17:10

from django.db import migrations


def seed_roles(apps, schema_editor):
    Role = apps.get_model('employees', 'Role')
    defaults = [
        {
            'name': 'Admin',
            'portal': 'Admin',
            'permissions': ['*'],
            'is_system': True,
        },
        {
            'name': 'HR',
            'portal': 'Admin',
            'permissions': [
                'portal.admin',
                'dashboard.view',
                'employees.view',
                'employees.manage',
                'employees.view_salary',
                'employees.view_bank',
                'org_chart.view',
                'leave.view',
                'leave.manage',
                'attendance.view',
                'attendance.manage',
                'payroll.view',
                'payroll.manage',
                'performance.view',
                'performance.manage',
                'recruitment.view',
                'recruitment.manage',
                'settings.view',
                'settings.manage',
                'offer_letters.view',
                'offer_letters.manage',
                'roles.manage',
            ],
            'is_system': True,
        },
        {
            'name': 'Employee',
            'portal': 'Employee',
            'permissions': [
                'portal.employee',
                'dashboard.view',
                'employees.self_view',
                'leave.self',
                'attendance.self',
            ],
            'is_system': True,
        },
    ]

    for data in defaults:
        Role.objects.update_or_create(
            name=data['name'],
            defaults={
                'portal': data['portal'],
                'permissions': data['permissions'],
                'is_system': data['is_system'],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_role_alter_employee_role'),
    ]

    operations = [
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]
