# Generated by Django 6.0 on 2025-12-24

from django.db import migrations


def update_role_permissions(apps, schema_editor):
    Role = apps.get_model('employees', 'Role')
    updates = {
        'Admin': [
            '*',
        ],
        'HR': [
            'portal.admin',
            'dashboard.view',
            'employees.view',
            'employees.manage',
            'employees.view_salary',
            'employees.view_bank',
            'org_chart.view',
            'onboarding.view',
            'onboarding.manage',
            'assets.view',
            'assets.manage',
            'policies.view',
            'policies.manage',
            'leave.view',
            'leave.manage',
            'attendance.view',
            'attendance.manage',
            'timesheet.view',
            'timesheet.manage',
            'overtime.view',
            'overtime.manage',
            'payroll.view',
            'payroll.manage',
            'claims.view',
            'claims.manage',
            'performance.view',
            'performance.manage',
            'recruitment.view',
            'recruitment.manage',
            'settings.view',
            'settings.manage',
            'offer_letters.view',
            'offer_letters.manage',
            'roles.manage',
        ],
        'Employee': [
            'portal.employee',
            'dashboard.view',
            'employees.self_view',
            'onboarding.self',
            'assets.self',
            'policies.self',
            'leave.self',
            'attendance.self',
            'timesheet.self',
            'overtime.self',
            'payroll.self',
            'claims.self',
        ],
    }

    for role_name, permissions in updates.items():
        Role.objects.filter(name=role_name, is_system=True).update(permissions=permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_update_role_permissions'),
    ]

    operations = [
        migrations.RunPython(update_role_permissions, migrations.RunPython.noop),
    ]
