# Generated by ChatGPT on 2026-02-06

from django.db import migrations


def seed_manager_role(apps, schema_editor):
    Role = apps.get_model('employees', 'Role')

    Role.objects.update_or_create(
        name='Manager',
        defaults={
            'portal': 'Employee',
            'permissions': [
                'portal.employee',
                'dashboard.view',
                'employees.self_view',
                'onboarding.self',
                'assets.self',
                'policies.self',
                'leave.self',
                'attendance.self',
                'timesheet.self',
                'overtime.self',
                'payroll.self',
                'claims.self',
                'performance.view',
                'performance.manage',
            ],
            'is_system': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_update_role_permissions_phase3'),
    ]

    operations = [
        migrations.RunPython(seed_manager_role, migrations.RunPython.noop),
    ]
