# Generated by Django 6.0 on 2025-12-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50)),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_postings', to='employees.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='employees.department')),
            ],
            options={
                'db_table': 'job_postings',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Interviewed', 'Interviewed'), ('Shortlisted', 'Shortlisted'), ('Hired', 'Hired'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=20)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('offer_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20, null=True)),
                ('offer_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hired_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_record', to='employees.employee')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting')),
            ],
            options={
                'db_table': 'recruitment',
                'ordering': ['-created_at'],
            },
        ),
    ]
