# Generated by Django 6.0 on 2025-12-24 15:35

import django.db.models.deletion
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentIntegration',
            fields=[
                ('integration_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Naukri', 'Naukri')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_post_jobs', models.BooleanField(default=True)),
                ('auto_sync_applicants', models.BooleanField(default=True)),
                ('credentials', models.JSONField(blank=True, null=True)),
                ('webhook_token', models.CharField(default=recruitment.models.default_webhook_token, max_length=64, unique=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_sync_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recruitment_integrations',
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='recruitment',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='source_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='source_provider',
            field=models.CharField(choices=[('Manual', 'Manual'), ('LinkedIn', 'LinkedIn'), ('Naukri', 'Naukri')], default='Manual', max_length=20),
        ),
        migrations.CreateModel(
            name='JobPostingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_job_url', models.URLField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, max_length=20, null=True)),
                ('sync_message', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_links', to='recruitment.jobposting')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='recruitment.recruitmentintegration')),
            ],
            options={
                'db_table': 'job_posting_integrations',
                'ordering': ['-updated_at'],
                'unique_together': {('job_posting', 'integration')},
            },
        ),
    ]
