# Generated by Django 5.2.11 on 2026-02-06 12:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_update_role_permissions_phase3'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluation_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('kpi_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('JOB_SPECIFIC', 'Job Specific'), ('STRATEGIC', 'Strategic')], default='GENERAL', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('related_role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='employees.department')),
            ],
            options={
                'db_table': 'kpis',
                'ordering': ['-is_active', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('final_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='performance.evaluationperiod')),
            ],
            options={
                'db_table': 'performance_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='performance.kpi')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance.performancereview')),
            ],
            options={
                'db_table': 'performance_review_items',
                'ordering': ['kpi__title'],
            },
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('employee', 'period'), name='unique_employee_period_review'),
        ),
        migrations.AddConstraint(
            model_name='performancereviewitem',
            constraint=models.UniqueConstraint(fields=('review', 'kpi'), name='unique_review_kpi'),
        ),
    ]
