# Generated by Django 6.0 on 2025-12-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('AccessCard', 'Access Card'), ('Monitor', 'Monitor'), ('Other', 'Other')], max_length=20)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Repair', 'Repair'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklistTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_checklist_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr_ops.asset')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='employees.employee')),
            ],
            options={
                'db_table': 'asset_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('ID', 'Identity Proof'), ('Bank', 'Bank Details'), ('Tax', 'Tax Document'), ('Contract', 'Employment Contract'), ('Other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskTemplate',
            fields=[
                ('task_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee')], default='Employee', max_length=20)),
                ('due_offset_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='hr_ops.onboardingchecklisttemplate')),
            ],
            options={
                'db_table': 'onboarding_task_templates',
                'ordering': ['task_template_id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee')], default='Employee', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='employees.employee')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hr_ops.onboardingtasktemplate')),
            ],
            options={
                'db_table': 'onboarding_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('require_ack', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to='employees.employee')),
            ],
            options={
                'db_table': 'policies',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('acknowledgment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('Declined', 'Declined')], default='Acknowledged', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='employees.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='hr_ops.policy')),
            ],
            options={
                'db_table': 'policy_acknowledgments',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('policy', 'employee')},
            },
        ),
    ]
