# Generated by Django 6.0 on 2025-12-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('structure_id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('provident_fund_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee')),
            ],
            options={
                'db_table': 'salary_structures',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('payslip_generated', models.BooleanField(default=False)),
                ('payslip_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll',
                'ordering': ['-pay_period_start', '-pay_period_end'],
                'unique_together': {('employee', 'pay_period_start', 'pay_period_end')},
            },
        ),
    ]
