# Generated by Django 6.0 on 2025-12-24 16:18

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0003_emailsettings_offerlettertemplate_employee_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricIntegration',
            fields=[
                ('integration_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('ZKTeco', 'ZKTeco'), ('eSSL', 'eSSL'), ('BioStar', 'BioStar'), ('Suprema', 'Suprema'), ('Generic', 'Generic')], default='Generic', max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('Webhook', 'Webhook'), ('Polling', 'Polling')], default='Webhook', max_length=20)),
                ('base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credentials', models.JSONField(blank=True, null=True)),
                ('data_mapping', models.JSONField(blank=True, null=True)),
                ('webhook_token', models.CharField(default=attendance.models.default_biometric_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_sync', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_sync_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biometric_integrations',
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricPunch',
            fields=[
                ('punch_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('punch_time', models.DateTimeField()),
                ('direction', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_punches', to='employees.employee')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='attendance.biometricintegration')),
            ],
            options={
                'db_table': 'biometric_punches',
                'ordering': ['-punch_time'],
            },
        ),
    ]
